### ISSUE TITLE
run  Gomoku game  , 'OpenAIChatWrapper' object has no attribute 'format'[Bug]:

### ISSUE THREAD

**Issue by BarryYin** [modelscope/agentscope#118]
run the  Gomoku game   with  python game_gomoku.py

(agentscope) mac@macmingdeMacBook-Pro code % python game_gomoku.py
2024-03-29 10:11:34.770 | INFO     | agentscope.models:read_model_configs:171 - Load configs for model wrapper: gpt-4
2024-03-29 10:11:34.773 | INFO     | agentscope.utils.monitor:_create_monitor_table:341 - Init [monitor_metrics] as the monitor table
2024-03-29 10:11:34.773 | INFO     | agentscope.utils.monitor:_create_monitor_table:342 - Init [monitor_metrics_quota_exceeded] as the monitor trigger
2024-03-29 10:11:34.773 | INFO     | agentscope.utils.monitor:__init__:311 - SqliteMonitor initialization completed at [./runs/run_20240329-101134_v5sm2q/agentscope.db]
2024-03-29 10:11:34.775 | INFO     | agentscope.models.model:__init__:239 - Initialize model [gpt-4]
2024-03-29 10:11:34.833 | INFO     | agentscope.utils.monitor:register_budget:554 - set budget None to gpt-4
2024-03-29 10:11:34.834 | INFO     | agentscope.utils.monitor:register:362 - Register metric [gpt-4.cost] to SqliteMonitor with unit [dollor] and quota [None]
2024-03-29 10:11:34.835 | INFO     | agentscope.utils.monitor:register:362 - Register metric [gpt-4.prompt_tokens] to SqliteMonitor with unit [token] and quota [None]
2024-03-29 10:11:34.837 | INFO     | agentscope.utils.monitor:register:362 - Register metric [gpt-4.completion_tokens] to SqliteMonitor with unit [token] and quota [None]
2024-03-29 10:11:34.838 | INFO     | agentscope.utils.monitor:register:362 - Register metric [gpt-4.total_tokens] to SqliteMonitor with unit [token] and quota [None]
2024-03-29 10:11:34.839 | INFO     | agentscope.models.model:__init__:239 - Initialize model [gpt-4]
2024-03-29 10:11:34.879 | INFO     | agentscope.utils.monitor:register_budget:554 - set budget None to gpt-4
Host: Welcome to the Gomoku game! Black player goes first. Please make your move.
Traceback (most recent call last):
  File "/Users/mac/Documents/GitHub/agentscope/examples/game_gomoku/code/game_gomoku.py", line 82, in <module>
    msg = player(msg)
  File "/Users/mac/Documents/GitHub/Guess_the_riddles/agentscope/src/agentscope/agents/agent.py", line 119, in __call__
    res = self.reply(*args, **kwargs)
  File "/Users/mac/Documents/GitHub/agentscope/examples/game_gomoku/code/gomoku_agent.py", line 58, in reply
    prompt = self.model.format(
AttributeError: 'OpenAIChatWrapper' object has no attribute 'format'

**Comment by DavdGao** [comment]
Please pull the latest code from GitHub and install in editable mode by `pip install -e .`

We will update pypi as soon as possible. Thanks for your attention!

**Comment by BarryYin** [comment]
thanks ,it's work

**Comment by DavdGao** [comment]
If you have any further questions or concerns, please feel free to create a new issue. Closing this for now.
