### ISSUE TITLE
[Bug]: run conversation_with_react_agent.py occur 'NoneType' object is not callable

### ISSUE THREAD

**Issue by BarryYin** [modelscope/agentscope#120]
(agentscope) mac@macmingdeMacBook-Pro code % python conversation_with_react_agent.py
Traceback (most recent call last):
  File "/Users/mac/Documents/GitHub/agentscope/examples/conversation_with_react_agent/code/conversation_with_react_agent.py", line 69, in <module>
    ServiceFactory.get(bing_search, api_key=BING_API_KEY, num_results=3),
  File "/Users/mac/Documents/GitHub/agentscope/src/agentscope/service/service_factory.py", line 101, in get
    docstring = parse(service_func.__doc__)
TypeError: 'NoneType' object is not callable

**Comment by DavdGao** [comment]
Please install docstring_parser by `pip install docstring_parser`, we will add a warning here to remind user to install necessary packages.

**Comment by BarryYin** [comment]
it's ok
