### ISSUE TITLE
Issue with test_gemini_chat (gemini_test.GeminiModelWrapperTest)

### ISSUE THREAD

**Issue by zyzhang1130** [modelscope/agentscope#234]
It seems the current test_gemini_chat (gemini_test.GeminiModelWrapperTest) is not compatible with `response.candidates`, and I got the following error in pr `Gemini chat wrapper fix` due to this reason.:
```
ERROR: test_gemini_chat (gemini_test.GeminiModelWrapperTest)
Test for chat API.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/agentscope/agentscope/tests/gemini_test.py", line 62, in test_gemini_chat
    response = model(contents="Hi!")
  File "/home/runner/work/agentscope/agentscope/src/agentscope/models/model.py", line 117, in checking_wrapper
    return model_call(self, *args, **kwargs)
  File "/home/runner/work/agentscope/agentscope/src/agentscope/models/gemini_model.py", line 153, in __call__
    if response.candidates:
AttributeError: 'DummyResponse' object has no attribute 'candidates'
```
However, I think `response.candidates` is essential for error handling in the event that `response` returned from API does not contain any text (see the pr `Gemini chat wrapper fix` for details).

**Comment by DavdGao** [comment]
Thanks for your report, and we will fix this bug as soon as possible.
