### ISSUE TITLE
[Bug]: 智谱 prompt 参数非法。请检查文档

### ISSUE THREAD

**Issue by kenneth-bro** [modelscope/agentscope#258]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**
使用openai客户端调用 one-api代理的智谱glm-4模型时，报错 
`{'code': 1214, 'message': 'prompt 参数非法。请检查文档。 (request id: 20240525111717334814010jvX7fM7r)', 'param': '', 'type': 'zhipu_error'}`

还有如果报错，应该提示出来才对，否则问题太难排查。

**To Reproduce**

**Code**
```
model_config_name = "glm-4"
# 使用qwen大模型初始化一个对话agent
dialog_agent = DialogAgent(
    name="assistant",
    sys_prompt="你是一个助手.",  # sys_prompt可以自行定义，不能为空
    model_config_name=model_config_name
)
user_agent = UserAgent(name="客户")

msg = Msg(name="小助手", content="介绍下你自己")
dialog_agent(msg)

```

**Expected behavior**

**Error messages**

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1535, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/kenneth/My/Codes/11-Python/LLMs/ai-chat-report/tests/agent_test.py", line 33, in <module>
    dialog_agent(msg)
  File "/Users/kenneth/anaconda3/envs/chat-report/lib/python3.10/site-packages/agentscope/agents/agent.py", line 294, in __call__
    res = self.reply(*args, **kwargs)
  File "/Users/kenneth/anaconda3/envs/chat-report/lib/python3.10/site-packages/agentscope/agents/dialog_agent.py", line 88, in reply
    response = self.model(prompt).text
  File "/Users/kenneth/anaconda3/envs/chat-report/lib/python3.10/site-packages/agentscope/models/model.py", line 117, in checking_wrapper
    return model_call(self, *args, **kwargs)
  File "/Users/kenneth/anaconda3/envs/chat-report/lib/python3.10/site-packages/agentscope/models/openai_model.py", line 210, in __call__
    self.update_monitor(call_counter=1, **response.usage.model_dump())
AttributeError: 'NoneType' object has no attribute 'model_dump'

**Environment (please complete the following information):**

- AgentScope Version: 0.0.4
- Python Version:  3.10
- OS: macOS

**Additional context**

**Comment by pan-x-c** [comment]
该问题是由于使用的 oneapi 的代理服务没有按照 openai 模型的返回格式返回 usage 域导致的。

agentscope 的 openai model 仅测试了 openai 官方接口，如果需使用第三方转发 api 需要根据第三方的接口格式做对应修改。例如这里描述的情况下，由于转发接口不包含 usage域，直接将报错的那一行代码（openai_model.py：line 210）注释掉即可。

**Comment by kenneth-bro** [comment]
> 该问题是由于使用的 oneapi 的代理服务没有按照 openai 模型的返回格式返回 usage 域导致的。
> 
> agentscope 的 openai model 仅测试了 openai 官方接口，如果需使用第三方转发 api 需要根据第三方的接口格式做对应修改。例如这里描述的情况下，由于转发接口不包含 usage域，直接将报错的那一行代码（openai_model.py：line 210）注释掉即可。

我这边排查了问题，最终不是因为usage导致的，需要配置 `role = user` 就解决了。

**Comment by DavdGao** [comment]
The issue is closed for now. Feel free to open a new issue if needed.
