### ISSUE TITLE
[Bug]:post_api_chat error

### ISSUE THREAD

**Issue by jjm2001** [modelscope/agentscope#273]
**Describe the bug**
After setting the post_api_chat file configuration in model_configs, calling the local qwen or GLM3 API server reports a Failed to call the model with {'detail': 'Not Found'} error. The details of the error are as follows:

2024-06-05 11:20:44.840 | INFO     | agentscope.models:read_model_configs:176 - Load configs for model wrapper: glm3_config
2024-06-05 11:20:44.847 | INFO     | agentscope.utils.monitor:_create_monitor_table:396 - Init [monitor_metrics] as the monitor table
2024-06-05 11:20:44.847 | INFO     | agentscope.utils.monitor:_create_monitor_table:397 - Init [monitor_metrics_quota_exceeded] as the monitor trigger
2024-06-05 11:20:44.847 | INFO     | agentscope.utils.monitor:__init__:366 - SqliteMonitor initialization completed at [./runs/run_20240605-112044_90yjm6/agentscope.db]
2024-06-05 11:20:44.849 | INFO     | agentscope.models.model:__init__:201 - Initialize model by configuration [glm3_config]
2024-06-05 11:20:44.850 | WARNING  | agentscope.models.post_model:__call__:138 - Failed to call the model with requests.codes == 404, retry 2/3 times
2024-06-05 11:20:45.856 | WARNING  | agentscope.models.post_model:__call__:138 - Failed to call the model with requests.codes == 404, retry 3/3 times
2024-06-05 11:20:47.863 | ERROR    | agentscope.models.post_model:__call__:157 - {
    "url": "http://127.0.0.1:8000",
    "json": {
        "inputs": [
            {
                "role": "system",
                "name": "system",
                "content": "You are a helpful assistant"
            }
        ]
    },
    "headers": {}
}
Traceback (most recent call last):
  File "/root/jin/agents/agentscope/tests/self_test4.py", line 20, in <module>
    x = assistant_agent(x)
  File "/root/jin/agents/agentscope/src/agentscope/agents/agent.py", line 294, in __call__
    res = self.reply(*args, **kwargs)
  File "/root/jin/agents/agentscope/src/agentscope/agents/dialog_agent.py", line 88, in reply
    response = self.model(prompt).text
  File "/root/jin/agents/agentscope/src/agentscope/models/model.py", line 117, in checking_wrapper
    return model_call(self, *args, **kwargs)
  File "/root/jin/agents/agentscope/src/agentscope/models/post_model.py", line 158, in __call__
    raise RuntimeError(
RuntimeError: Failed to call the model with {'detail': 'Not Found'}

**To Reproduce**

1. My code
- Contents in Model_configs.json:
[
    {
        "model_type": "post_api_chat",
        "config_name": "glm3_config",
        "api_url": "http://127.0.0.1:8000",
        "headers": {},
        "json_args": {}
    }
]

My code:
import agentscope
from agentscope.agents import DialogAgent, UserAgent

# read model configs
agentscope.init(model_configs="./model_configs.json")

# Create a dialog agent and a user agent
assistant_agent = DialogAgent(
    name="Assistant",
    sys_prompt="You are a helpful assistant",
    model_config_name="glm3_config",
)

user_agent = UserAgent()

# Basic version
x = None
while x is None or x.content != "exit":
    x = assistant_agent(x)
    x = user_agent(x)

# Advanced version with sequential pipeline
from agentscope.pipelines.functional import sequentialpipeline
x = None
while x is None or x.content != "exit":
    x = sequentialpipeline([dialog_agent, user_agent], x)

# Advanced version with while loop pipeline
from agentscope.pipelines.functional import whilelooppipeline
x = whilelooppipeline(
    [assistant_agent, user_agent],
    condition_func= lambda _, x: x is None or x.content!="exit",
    x=None
)

**Comment by jjm2001** [comment]
resolved, to use ./scripts/flask_transformers/setup_hf_service.py to run api service instead of api server program in local LLM package. It runs normally now

**Comment by yawzhe** [comment]
post_api_chat没有流式输出呀
