### ISSUE TITLE
AgentScope Studio启动失败

### ISSUE THREAD

**Issue by wzsage** [modelscope/agentscope#281]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

重新拉取github上的最新代码，使用pip install -e. [full]安装，尝试运行
import agentscope

agentscope.studio.init()
报错如下：
C:\Users\wz\.conda\envs\agentscope\python.exe D:/pyproject/agentscope/local/test.py
Traceback (most recent call last):
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pyproject\agentscope\local\test.py", line 3, in <module>
    agentscope.studio.init()
  File "D:\pyproject\agentscope\src\agentscope\studio\_app.py", line 687, in init
    _db.create_all()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask_sqlalchemy\extension.py", line 900, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask_sqlalchemy\extension.py", line 881, in _call_for_binds
    getattr(metadata, op_name)(bind=engine)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\sql\schema.py", line 5857, in create_all
    bind._run_ddl_visitor(
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 3250, in _run_ddl_visitor
    with self.begin() as conn:
  File "C:\Users\wz\.conda\envs\agentscope\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 3240, in begin
    with self.connect() as conn:
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 3276, in connect
    return self._connection_cls(self)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 2440, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\base.py", line 3300, in raw_connection
    return self.pool.connect()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\sqlalchemy\engine\default.py", line 620, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

进程已结束,退出代码1

**Comment by DavdGao** [comment]
Will be fixed in #280

**Comment by DavdGao** [comment]
The bug is fixed, please pull the lasted code from GitHub repo, and we will update PyPI as soon as possible.
