### ISSUE TITLE
workstation运行后无法执行工作流

### ISSUE THREAD

**Issue by wzsage** [modelscope/agentscope#282]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

验证通过后，点击运行报错。
工作台报错：
Failed!
There was an error running your workflow.
后端报错如下：
127.0.0.1 - - [09/Jun/2024 22:45:13] "POST /convert-to-py HTTP/1.1" 500 -
[2024-06-09 22:45:21,964] ERROR in app: Exception on /convert-to-py [POST]
Traceback (most recent call last):
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\pyproject\agentscope\src\agentscope\studio\_app.py", line 477, in _convert_config_to_py
    status, py_code = _convert_to_py(content)
  File "D:\pyproject\agentscope\src\agentscope\studio\_app.py", line 197, in _convert_to_py
    from agentscope.web.workstation.workflow_dag import build_dag
  File "D:\pyproject\agentscope\src\agentscope\web\workstation\workflow_dag.py", line 42, in <module>
    class ASDiGraph(nx.DiGraph):
AttributeError: 'NoneType' object has no attribute 'DiGraph'
127.0.0.1 - - [09/Jun/2024 22:45:21] "POST /convert-to-py HTTP/1.1" 500 -
127.0.0.1 - - [09/Jun/2024 22:45:39] "GET /static/html-drag-components/service-read-text.html HTTP/1.1" 200 -
[2024-06-09 22:46:03,982] ERROR in app: Exception on /convert-to-py-and-run [POST]
Traceback (most recent call last):
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\wz\.conda\envs\agentscope\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\pyproject\agentscope\src\agentscope\studio\_app.py", line 495, in _convert_config_to_py_and_run
    status, py_code = _convert_to_py(
  File "D:\pyproject\agentscope\src\agentscope\studio\_app.py", line 197, in _convert_to_py
    from agentscope.web.workstation.workflow_dag import build_dag
  File "D:\pyproject\agentscope\src\agentscope\web\workstation\workflow_dag.py", line 42, in <module>
    class ASDiGraph(nx.DiGraph):
AttributeError: 'NoneType' object has no attribute 'DiGraph'
127.0.0.1 - - [09/Jun/2024 22:46:03] "POST /convert-to-py-and-run HTTP/1.1" 500 -

**Comment by pan-x-c** [comment]
Try `pip install networkx` or install the full version.

**Comment by wzsage** [comment]
> Try `pip install networkx` or install the full version.

thx it solved
