### ISSUE TITLE
[Bug]:No module named 'agentscope.web.studio.studio'

### ISSUE THREAD

**Issue by NeilWang079** [modelscope/agentscope#302]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**
Traceback (most recent call last):
  File "D:\anaconda3\envs\agentscope\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\envs\agentscope\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\agentscope\Scripts\as_studio.exe\__main__.py", line 4, in <module>
    from agentscope.web.studio.studio import run_app
ModuleNotFoundError: No module named 'agentscope.web.studio.studio'

**Comment by pan-x-c** [comment]
The `agentscope.web.studio` module is already removed in the newest version, please reinstall AgentScope using `pip install -e .`

**Comment by NeilWang079** [comment]
Thanks for the answer.
