### ISSUE TITLE
[Bug]: bug in DictDialogAgent when use_memory = False

### ISSUE THREAD

**Issue by wujiren** [modelscope/agentscope#338]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**
In DictDialogAgent , if you set **use_memory = False**, the source code in reply() method will raise error
```python
        self.memory.add(
            Msg(self.name, self.parser.to_memory(res.parsed), "assistant"),
        )
```
Reason: self.memory is None

**To Reproduce**
1. source code
```python
import agentscope
from agentscope.agents import DictDialogAgent
from agentscope.message import Msg
from agentscope.parsers import MarkdownJsonDictParser

if __name__ == "__main__":
    agentscope.init(model_configs="yor configs", logger_level="DEBUG")
    parser = MarkdownJsonDictParser(content_hint={"reply": "your reply"})
    agent = DictDialogAgent(
        name="Agent",
        sys_prompt="you are an agent\n{content_hint}",
        model_config_name="your config name",
        use_memory=False, // this is when the error will be raised
    )
    agent.set_parser(parser)
    x = agent(Msg("user", "I'm testing you"))

```
**Expected behavior**
nothing

**Error messages**
```
Traceback (most recent call last):
  File "/Volumes/work/workspace/llm/writing/test_error.py", line 18, in <module>
    x = agent(Msg("user", "I'm testing you"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jirenwu/anaconda3/envs/chatgpt/lib/python3.11/site-packages/agentscope/agents/agent.py", line 296, in __call__
    res = self.reply(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jirenwu/anaconda3/envs/chatgpt/lib/python3.11/site-packages/agentscope/agents/dict_dialog_agent.py", line 111, in reply
    self.memory.add(
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'add'
```
**Environment (please complete the following information):**

- AgentScope Version: ['0.0.6alpha3]
- Python Version: [3.11]
- OS: [macoss]

**Additional context**
maybe you should:
```python
    if self.memory: 
        self.memory.add(
            Msg(self.name, self.parser.to_memory(res.parsed), "assistant"),
        )
```

**Comment by DavdGao** [comment]
Thanks for your reporting, we will fix it as soon as possible.
