### ISSUE TITLE
[Bug]: Quickstart fails to run!

### ISSUE THREAD

**Issue by GuillaumeWRLD** [modelscope/agentscope#430]
**<u>AgentScope is an open-source project. To involve a broader community, we recommend asking your questions in English.</u>**

**Describe the bug**

Quickstart fails to run

**To Reproduce**

Code:

import agentscope

azure_cfg_dict = {
    "config_name": "lite_llm_azure",
    "model_type": "litellm_chat",
    "model_name": "gpt-4",
    "api_key": "xxx",
    "api_base": "xxx",
    "api_version": "xxx",
},

agentscope.init(model_configs=[openai_cfg_dict])

dialogAgent = DialogAgent(name="assistant", model_config_name="gpt-4", sys_prompt="You are a helpful ai assistant")

from agentscope.message import Msg

message_from_alice = Msg("Alice", "Hi!")

print(dialogAgent(message_from_alice))

**Expected behavior**
Correct output

**Error messages**
```
Traceback (most recent call last):
  File "/Users/mikelueck/GitHub/agentscope_playground/main.py", line 1, in <module>
    import agentscope
  File "/Users/mikelueck/Library/Caches/pypoetry/virtualenvs/muser-scene-agent-BPyGuuEz-py3.11/lib/python3.11/site-packages/agentscope/__init__.py", line 5, in <module>
    from . import agents
  File "/Users/mikelueck/Library/Caches/pypoetry/virtualenvs/muser-scene-agent-BPyGuuEz-py3.11/lib/python3.11/site-packages/agentscope/agents/__init__.py", line 3, in <module>
    from .agent import AgentBase, DistConf
  File "/Users/mikelueck/Library/Caches/pypoetry/virtualenvs/muser-scene-agent-BPyGuuEz-py3.11/lib/python3.11/site-packages/agentscope/agents/agent.py", line 17, in <module>
    from agentscope.memory import TemporaryMemory
  File "/Users/mikelueck/Library/Caches/pypoetry/virtualenvs/muser-scene-agent-BPyGuuEz-py3.11/lib/python3.11/site-packages/agentscope/memory/__init__.py", line 8, in <module>
    from .temporary_memory import TemporaryMemory
  File "/Users/mikelueck/Library/Caches/pypoetry/virtualenvs/muser-scene-agent-BPyGuuEz-py3.11/lib/python3.11/site-packages/agentscope/memory/temporary_memory.py", line 17, in <module>
    from ..service.retrieval.retrieval_from_list import retrieve_from_list
  File "/Users/mikelueck/Library/Caches/pypoetry/virtualenvs/muser-scene-agent-BPyGuuEz-py3.11/lib/python3.11/site-packages/agentscope/service/__init__.py", line 29, in <module>
    from .multi_modality.dashscope_services import (
ModuleNotFoundError: No module named 'agentscope.service.multi_modality'
```

**Environment (please complete the following information):**
```
 [tool.poetry.dependencies]
 python = "^3.11"
 agentscope = "^0.0.5"
```

- AgentScope Version: 0.0.5
- Python Version: 3.11
- OS: MacOS

**Additional context**

**Comment by pan-x-c** [comment]
Version 0.0.5 is stale. Please clone the repository and install it with `pip install -e .`

**Comment by GuillaumeWRLD** [comment]
Can't we have a stable version? If you expect ppl to use AgentScope in production?

**Comment by DavdGao** [comment]
@GuillaumeWRLD Thanks for your suggestion. A new stable version will be available in a few days

**Comment by DavdGao** [comment]
A new vision v0.1.0 is updated in Pypi and GitHub. Feel free to open a new issue if neededd, closing this for now.
