### ISSUE TITLE
how to fix it?"ollama._types.ResponseError"

### ISSUE THREAD

**Issue by JunmingRen** [modelscope/agentscope#437]
Traceback (most recent call last):
  File "/home/mingjun/agentscope/family_test/test.py", line 32, in <module>
    x = dialogAgent(x)
  File "/home/mingjun/agentscope/src/agentscope/agents/agent.py", line 278, in __call__
    res = self.reply(*args, **kwargs)
  File "/home/mingjun/agentscope/src/agentscope/agents/dialog_agent.py", line 76, in reply
    response = self.model(prompt)
  File "/home/mingjun/agentscope/src/agentscope/models/model.py", line 115, in checking_wrapper
    return model_call(self, *args, **kwargs)
  File "/home/mingjun/agentscope/src/agentscope/models/ollama_model.py", line 198, in __call__
    response = self.client.chat(**kwargs)
  File "/mnt/data/mingjun/anaconda3/envs/agentscope/lib/python3.9/site-packages/ollama/_client.py", line 180, in chat
    return self._request_stream(
  File "/mnt/data/mingjun/anaconda3/envs/agentscope/lib/python3.9/site-packages/ollama/_client.py", line 98, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
  File "/mnt/data/mingjun/anaconda3/envs/agentscope/lib/python3.9/site-packages/ollama/_client.py", line 74, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError

it happens like above, when i try to get its response?

**Comment by DavdGao** [comment]
Can you provide more details? e.g. the model you are using, and the source code

**Comment by JunmingRen** [comment]
解决了。用的ollama本地模型，要把梯子关了
