### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by MoQijie** [modelscope/agentscope#451]
**Describe the bug**
Traceback (most recent call last):
File "/root/agentscope/agentscope-main/examples/conversation_with_RAG_agents/rag_example.py", line 150， in <module> main( )
File "/root/agentscope/agentscope-main/examples/conversation_with_RAG_agents/rag_example.py",line 86, in main knowledge bank.equip(agent，agent.knowledge id list)
File "/root/agentscope/agentscope-main/src/agentscope/rag/knowledge_bank.py", line 188, in equip knowledge = self.get_knowledge(
File "/root/agentscope/agentscope-main/src/agentscope/rag/knowledge_bank.py", line 156, in get_knowledge
raise ValueError(
ValueError: agentscope_tutorial_rag does not exist in the knowledge bank.

**Expected behavior**
When I get the above error when I clone the entire project to test the RAG, would anyone be willing to help me analyze the following?

**Environment (please complete the following information):**

- AgentScope Version:v0.1.0
- Python Version: 3.10
- OS: ubuntu

**Comment by MoQijie** [comment]
Sorry to bother you guys, it's all my fault
<img width="914" alt="_20240925181136" src="https://github.com/user-attachments/assets/b88d863a-1094-4fac-b99a-16dc3922f402">
