### ISSUE TITLE
 [Bug]: Error occurs while using gemini

### ISSUE THREAD

**Issue by TianCai19** [modelscope/agentscope#80]
**Describe the bug**
When i try to run my first easy agentscope demo with gemini api ,a error happened .
**To Reproduce**
1. My code 
```python
from agentscope.message import Msg
import agentscope
import agentscope
from agentscope.agents import DialogAgent, UserAgent

agentscope.init(model_configs=       
            {
            "model_type": "gemini_chat",
            "config_name": "gemini",
            "model": "gemini-pro",
            "api_key": "AIzaSyD28CiLXcwzIiycOiD****",  # Load from env if not provided
        })

dialogAgent = DialogAgent(name="assistant", model_config_name="gemini", sys_prompt="You are a helpful ai assistant")
userAgent = UserAgent()

message_from_alice = Msg("Alice", "Hi!")
```
2. How to execute 
I download the newest code form the repo
and install with a new conda env
```bash
# Pull the source code from GitHub
git clone https://github.com/modelscope/agentscope.git

# Install the package in editable mode
cd AgentScope
pip install -e .
```

4. Error :
```
(agentscope) (base) zz@MacBook-Pro-Cody multi-agent % python3 -u "/Users/zz/code/m
ulti-agent/try.py"
2024-03-17 08:54:09.776 | INFO     | agentscope.models:read_model_configs:171 - Load configs for model wrapper: gemini
2024-03-17 08:54:09.780 | INFO     | agentscope.utils.monitor:_create_monitor_table:341 - Init [monitor_metrics] as the monitor table
2024-03-17 08:54:09.780 | INFO     | agentscope.utils.monitor:_create_monitor_table:342 - Init [monitor_metrics_quota_exceeded] as the monitor trigger
2024-03-17 08:54:09.780 | INFO     | agentscope.utils.monitor:__init__:311 - SqliteMonitor initialization completed at [./runs/run_20240317-085409_pf2yha/agentscope.db]
Traceback (most recent call last):
  File "/Users/zz/code/multi-agent/try.py", line 17, in <module>
    dialogAgent = DialogAgent(name="assistant", model_config_name="gemini", sys_prompt="You are a helpful ai assistant")
  File "/Users/zz/code/agentscope/src/agentscope/agents/agent.py", line 21, in __call__
    instance = super().__call__(*args, **kwargs)
  File "/Users/zz/code/agentscope/src/agentscope/agents/dialog_agent.py", line 44, in __init__
    super().__init__(
  File "/Users/zz/code/agentscope/src/agentscope/agents/agent.py", line 68, in __init__
    self.model = load_model_by_config_name(model_config_name)
  File "/Users/zz/code/agentscope/src/agentscope/models/__init__.py", line 117, in load_model_by_config_name
    return _get_model_wrapper(model_type=model_type)(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'model_name'
```

**Expected behavior**
just run the demo successfully 

**Environment (please complete the following information):**
 - AgentScope Version: [ 0.0.1 via `print(agentscope.__version__)`]
 - Python Version: 3.9
 - OS:  macos

**Comment by ZiTao-Li** [comment]
As the error report says, can you modify the "model" key word to "model_name" in your model config dict? Let us know if it still reports errors.

**Comment by ZiTao-Li** [comment]
As the error report says, can you modify the "model" key word to "model_name" in your model config dict? Let us know if it still reports errors.

**Comment by DavdGao** [comment]
Example configuration for Gemini Chat Wrapper is also available in https://modelscope.github.io/agentscope/en/tutorial/203-model.html#gemini-api

**Comment by DavdGao** [comment]
If you have any further questions or concerns, please feel free to create a new issue. Closing this for now.
